dist: xenial

language: python
python:
  - "3.8.5"

notifications:
  email:
#    - bizon@renci.org
    - powen@renci.org

before_install:
  - git lfs pull

services:
  - redis-server

# command to install dependencies
install:
  - pip install -r requirements.txt
  - cat requirements.txt

env:
  global:
    - PYTHONPATH=$PWD

# command to run tests
script:
  - python src/graph_coalescence/load_redis.py test
  - pytest -p no:warnings tests

after_success:
  - coveralls
