apiVersion: v1
items:

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ac-web-dep
    labels:
      service: ac-web-service
  spec:
    replicas: 1
    selector:
      matchLabels:
        service: ac-web-service
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: ac-web-service
      spec:
        containers:
        - name: ac-web
          image: renciorg/ac
          ports:
            - containerPort: 6380
          resources: {}
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /data
              name: ac-web-data-volume
        volumes:
          - name: ac-web-data-volume
            persistentVolumeClaim:
              claimName: ac-web-data-pvc
        restartPolicy: Always
  status: {}

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: ac-web-service
    name: ac-web-service
  spec:
    type: NodePort
    selector:
      service: ac-web-service
    ports:
      - name: '6380'
        port: 6380
kind: List
metadata: {}